### ISSUE TITLE
HotKey to open Repl is currently CMD+W which is a system hotkey to close tab

### ISSUE THREAD

**Issue by waldnzwrld** [tpae/node-repl#14]
When Node Repl is installed the default hotkey is CMD+W which is an OS X hotkey to close a tab. 

Expected behavior: Hotkey is set to something other than a necessary system hotkey (OPT+CMD+R, OPT+CMD+W)

Current Behavior: Hotkey is set to CMD+W which hinders OS X workflow.

**Comment by tpae** [comment]
I've merged your pull request and released `0.5.0`. Thank you!
